-- Executar no schema TREINAMENTO

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER TRG_CLIENTE_BI';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4080 THEN -- trigger does not exist
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER TRG_CLIENTE_BU';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4080 THEN -- trigger does not exist
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP PACKAGE PKG_CLIENTE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN -- object does not exist
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE TB_CLIENTE CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN -- table or view does not exist
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CLIENTE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN -- sequence does not exist
      RAISE;
    END IF;
END;
/