-- TREINAMENTO.TB_CLIENTE definição

CREATE TABLE "TREINAMENTO"."TB_CLIENTE" 
   (	"ID_CLIENTE" NUMBER(10,0) NOT NULL ENABLE, 
	"NOME" VARCHAR2(200) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(200), 
	"CEP" VARCHAR2(8), 
	"LOGRADOURO" VARCHAR2(200), 
	"BAIRRO" VARCHAR2(100), 
	"CIDADE" VARCHAR2(100), 
	"UF" CHAR(2), 
	"ATIVO" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	"DT_CRIACAO" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"DT_ATUALIZACAO" TIMESTAMP (6), 
	 CONSTRAINT "CK_TB_CLIENTE_ATIVO" CHECK (ATIVO IN (0,1)) ENABLE, 
	 CONSTRAINT "CK_TB_CLIENTE_UF" CHECK (UF IN (
        'AC','AL','AP','AM','BA','CE','DF','ES','GO',
        'MA','MT','MS','MG','PA','PB','PR','PE','PI',
        'RJ','RN','RS','RO','RR','SC','SP','SE','TO'
    )) ENABLE, 
	 CONSTRAINT "PK_TB_CLIENTE" PRIMARY KEY ("ID_CLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "UK_TB_CLIENTE_EMAIL" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE OR REPLACE EDITIONABLE TRIGGER "TREINAMENTO"."TRG_CLIENTE_BI" 
BEFORE INSERT ON TB_CLIENTE
FOR EACH ROW
BEGIN
    IF :NEW.ID_CLIENTE IS NULL THEN
        SELECT SEQ_CLIENTE.NEXTVAL
          INTO :NEW.ID_CLIENTE
          FROM DUAL;
    END IF;
    IF :NEW.DT_CRIACAO IS NULL THEN
        :NEW.DT_CRIACAO := SYSTIMESTAMP;
    END IF;
END;
/
ALTER TRIGGER "TREINAMENTO"."TRG_CLIENTE_BI" ENABLE;
  CREATE OR REPLACE EDITIONABLE TRIGGER "TREINAMENTO"."TRG_CLIENTE_BU" 
BEFORE UPDATE ON TB_CLIENTE
FOR EACH ROW
BEGIN
    :NEW.DT_ATUALIZACAO := SYSTIMESTAMP;
END;
/
ALTER TRIGGER "TREINAMENTO"."TRG_CLIENTE_BU" ENABLE;

CREATE UNIQUE INDEX "TREINAMENTO"."PK_TB_CLIENTE" ON "TREINAMENTO"."TB_CLIENTE" ("ID_CLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "TREINAMENTO"."UK_TB_CLIENTE_EMAIL" ON "TREINAMENTO"."TB_CLIENTE" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;