CREATE OR REPLACE TRIGGER TREINAMENTO.TRG_CLIENTE_BI
BEFORE INSERT ON TB_CLIENTE
FOR EACH ROW
BEGIN
    IF :NEW.ID_CLIENTE IS NULL THEN
        SELECT SEQ_CLIENTE.NEXTVAL
          INTO :NEW.ID_CLIENTE
          FROM DUAL;
    END IF;
    IF :NEW.DT_CRIACAO IS NULL THEN
        :NEW.DT_CRIACAO := SYSTIMESTAMP;
    END IF;
END;