CREATE OR REPLACE PACKAGE TREINAMENTO.PKG_CLIENTE AS
  FUNCTION FN_VALIDAR_EMAIL(p_email VARCHAR2) RETURN NUMBER;
  FUNCTION FN_NORMALIZAR_CEP(p_cep VARCHAR2) RETURN VARCHAR2;
  PROCEDURE PRC_VALIDAR_CLIENTE(
    p_nome  IN VARCHAR2,
    p_email IN VARCHAR2,
    p_cep   IN VARCHAR2,
    p_uf    IN VARCHAR2
  );
  PROCEDURE PRC_DELETAR_CLIENTE(p_id NUMBER);
  PROCEDURE PRC_LISTAR_CLIENTES(
    p_nome  IN VARCHAR2,
    p_email IN VARCHAR2,
    p_rc    OUT SYS_REFCURSOR
  );
PROCEDURE PRC_INSERIR_CLIENTE(
    p_nome        IN  TB_CLIENTE.NOME%TYPE,
    p_email       IN  TB_CLIENTE.EMAIL%TYPE,
    p_cep         IN  TB_CLIENTE.CEP%TYPE,
    p_logradouro  IN  TB_CLIENTE.LOGRADOURO%TYPE,
    p_bairro      IN  TB_CLIENTE.BAIRRO%TYPE,
    p_cidade      IN  TB_CLIENTE.CIDADE%TYPE,
    p_uf          IN  TB_CLIENTE.UF%TYPE,
    p_ativo       IN  TB_CLIENTE.ATIVO%TYPE,
    p_id          OUT TB_CLIENTE.ID_CLIENTE%TYPE
);